[servers.liberachat]
server = "irc.libera.chat"

nick_password_file = "NICKSERV_PASSWORD_FILE"

nickname = "zihadmahiuddin"
realname = "Zihad"
username = "zihad"

channels = ["#zig"]

should_ghost = true
